version: '3.4'

x-defaults: &defaults
  restart: unless-stopped
  build: .
  depends_on:
    - redis
    - postgres
    - memcached
    - smtp
  env_file: .env
  environment:
    SENTRY_MEMCACHED_HOST: memcached
    SENTRY_REDIS_HOST: redis
    SENTRY_POSTGRES_HOST: postgres
    SENTRY_EMAIL_HOST: smtp
  volumes:
    - sentry-data:/var/lib/sentry/files
  networks:
    - sentry

services:
  smtp:
    restart: unless-stopped
    image: tianon/exim4
    networks:
      - sentry

  memcached:
    restart: unless-stopped
    image: memcached:1.5-alpine
    networks:
      - sentry

  redis:
    restart: unless-stopped
    image: redis:3.2-alpine
    networks:
      - sentry

  postgres:
    restart: unless-stopped
    image: postgres:9.5-alpine
    volumes:
      - sentry-postgres:/var/lib/postgresql/data
    networks:
      - sentry
    environment:
      POSTGRES_USER: "${SENTRY_DB_USER}"
      POSTGRES_PASSWORD: "${SENTRY_DB_PASSWORD}"
      POSTGRES_DB: "${SENTRY_DB_NAME}"

  web:
    <<: *defaults
    ports:
      - '9000:9000'
    networks:
      - sentry
      - nginx-proxy
    environment:
      VIRTUAL_HOST: 'bugs.proto.energy'
      VIRTUAL_PORT: 9000
      LETSENCRYPT_HOST: 'bugs.proto.energy'
      LETSENCRYPT_EMAIL: 'domain.admin@proto.energy'

  cron:
    <<: *defaults
    command: run cron

  worker:
    <<: *defaults
    command: run worker

networks:
  nginx-proxy:
    external: true
  sentry:
    driver: bridge

volumes:
  sentry-data:
    external: true
  sentry-postgres:
    external: true
