# NOTE: This docker-compose.yml is meant to be just an example of how
# you could accomplish this on your own. It is not intended to work in
# all use-cases and must be adapted to fit your needs. This is merely
# a guideline.

# See docs.getsentry.com/on-premise/server/ for full
# instructions

version: '3.4'

x-defaults: &defaults
  restart: unless-stopped
  build: .
  depends_on:
    - redis
    - postgres
    - memcached
    - smtp
    - rabbitmq
  env_file: .env
  environment:
    SENTRY_MEMCACHED_HOST: memcached
    SENTRY_REDIS_HOST: redis
    SENTRY_POSTGRES_HOST: postgres
    SENTRY_EMAIL_HOST: smtp
  volumes:
    - sentry-data:/var/lib/sentry/files
  networks:
    - sentry

services:
  smtp:
    restart: unless-stopped
    image: tianon/exim4
    networks:
      - sentry

  memcached:
    restart: unless-stopped
    image: memcached:1.5-alpine
    networks:
      - sentry

  redis:
    restart: unless-stopped
    image: redis:3.2-alpine
    networks:
      - sentry

  postgres:
    restart: unless-stopped
    image: postgres:9.5-alpine
    volumes:
      - sentry-postgres:/var/lib/postgresql/data
    networks:
      - sentry
    environment:
      POSTGRES_USER: "${SENTRY_DB_USER}"
      POSTGRES_PASSWORD: "${SENTRY_DB_PASSWORD}"
      POSTGRES_DB: "${SENTRY_DB_NAME}"

  rabbitmq:
    restart: unless-stopped
    image: rabbitmq:3.7-management
    networks:
      - sentry
    environment:
      RABBITMQ_DEFAULT_USER: "${SENTRY_RABBITMQ_USERNAME}"
      RABBITMQ_DEFAULT_PASS: "${SENTRY_RABBITMQ_PASSWORD}"
      RABBITMQ_HIPE_COMPILE: 1

  web:
    <<: *defaults
    ports:
      - '9600:9000'
    networks:
      - sentry
      - nginx-proxy
    environment:
      VIRTUAL_HOST: 'bugs.proto.energy'
      VIRTUAL_PORT: 9600
      LETSENCRYPT_HOST: 'bugs.proto.energy'
      LETSENCRYPT_EMAIL: 'domain.admin@proto.energy'

  cron:
    <<: *defaults
    command: run cron

  worker:
    <<: *defaults
    command: run worker

networks:
  nginx-proxy:
    external: true
  sentry:
    driver: bridge

volumes:
  sentry-data:
    external: true
  sentry-postgres:
    external: true
